AWSTemplateFormatVersion: '2010-09-09'
Description: Hello World with SAM
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs8.10
    Timeout: 5
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
  addNumbers:
    Properties:
      CodeUri: s3://riyaz-sam/6740b7a0c975f8f01fed5134a4ebff34
      Events:
        PostAdd:
          Properties:
            Method: post
            Path: /add
          Type: Api
      Handler: add.handler
    Type: AWS::Serverless::Function
  eventLogger:
    Properties:
      CodeUri: s3://riyaz-sam/6740b7a0c975f8f01fed5134a4ebff34
      Events:
        FileUpload:
          Properties:
            Bucket:
              Ref: MyBucket
            Events: s3:ObjectCreated:*
          Type: S3
        GetLogs:
          Properties:
            Method: get
            Path: /logs
          Type: Api
      Handler: logger.handler
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
